### DISCUSSION TITLE
JS Framework Vote

### DISCUSSION THREAD

**Discussion by aslink87** [eddb2-0/EDDB-2.0-frontend#9] [Polls]
Hey team. Consider this a vote for framework. But it also serves as a way to evaluate contributor activity...

Svelte has been put forth by myself and @jbritian. Other than that React is an option. I haven't seen any discussions about other frameworks so unless someone makes the case (soon) they will be disregarded.

**Comment by pveeckhout** [comment]
there has been a stack vote a month or so ago:

```
 frontend:
    react:
      voters:
        - Garud
        - Ignalion
        - madmax
        - one_cog
      total: 4
    svelte:
      voters:
        - jbritain
      total: 1
````
